version: '3.7'

services:
  php-http:
    build:
      context: ./docker/php
    volumes:
      - ./php:/var/www/html
    networks:
      - php-backend
  nginx-http:
    build:
      context: ./docker/nginx
    volumes:
      - ./php:/var/www/html
    ports:
      - "3000:80"
    networks:
      - php-backend
  go-http:
    image: golang:1.14
    command: go run cmd/http.go
    working_dir: /go-http
    volumes:
      - ./golang:/go-http
    ports:
      - "3001:80"
networks:
  php-backend:
    driver: bridge
