version: '3.7'

services:
  php-http:
    build:
      context: ./docker/php
    volumes:
      - ./php:/var/www/html
    networks:
      - php-backend
  nginx-http:
    build:
      context: ./docker/nginx
    volumes:
      - ./php:/var/www/html
    ports:
      - "3000:80"
    networks:
      - php-backend
  go-http:
    build:
      context: ./docker/go/http
    working_dir: /go-http
    volumes:
      - ./golang:/go-http
    ports:
      - "3001:80"
    restart: always
  go-grpc:
    build:
      context: ./docker/go/grpc
    working_dir: /go-grpc
    volumes:
      - ./golang:/go-grpc
    ports:
      - "3002:80"
    restart: always
networks:
  php-backend:
    driver: bridge
