version: '3.7'

services:
  client:
    build:
      context: ./docker/php/client
    env_file:
      - ./docker/common.env
    working_dir: /client
    volumes:
      - ./php:/client
      - ./golang/api:/protos
    networks:
      - benchmark
  php-http:
    env_file:
      - ./docker/common.env
    build:
      context: ./docker/php/http
    volumes:
      - ./php:/var/www/html
    networks:
      - php-backend
  nginx-http:
    build:
      context: ./docker/nginx
    volumes:
      - ./php:/var/www/html
    ports:
      - "3000:80"
    networks:
      - php-backend
      - benchmark
  go-http:
    env_file:
      - ./docker/common.env
    build:
      context: ./docker/go/http
    working_dir: /go-http
    volumes:
      - ./golang:/go-http
      - ./php:/php-code
    ports:
      - "3001:80"
    networks:
      - benchmark
    restart: always
  go-grpc:
    env_file:
      - ./docker/common.env
    build:
      context: ./docker/go/grpc
    working_dir: /go-grpc
    volumes:
      - ./golang:/go-grpc
      - ./php:/php-code
    ports:
      - "3002:80"
    networks:
      - benchmark
    restart: always
  painter:
    build:
      context: ./docker/python
    working_dir: /painter
    volumes:
      - ./python:/painter
      - ./benchmarks:/data
networks:
  php-backend:
    driver: bridge
  benchmark:
    driver: bridge
